title: isaac broyles | home
description: Isaac Broyles' personal site featuring articles about Software Engineering
show_downloads: true
google_analytics: "UA-122362865-1"
repository: "isaacbroyles/isaacbroyles.github.io"
include: [".well-known"]
paginate: 5
url: "https://www.isaacbroyles.com"
author: isaacbroyles
twitter:
  username: isaacbroyles
  card: summary
logo: /assets/images/isaac_broyles_bw.png
social:
  name: Isaac Broyles
  links:
    - https://github.com/isaacbroyles
    - https://www.linkedin.com/in/isaacbroyles/
    - https://twitter.com/isaacbroyles
    - https://www.facebook.com/isaacbroyles
    - https://plus.google.com/+IsaacBroyles
    - https://keybase.io/isaacbroyles
    - http://youtube.com/c/IsaacBroyles
    - https://stackoverflow.com/users/977549/isaac-broyles
    - https://www.instagram.com/isaacbroyles/
webmaster_verifications:
  google: DqeN0Z1Vx-FCZ-80zzg0NSTfxl2r1WYFY-Pj6vXW50Q
  bing: 413A3B73496AD7A36C780F6503A74820
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: /assets/images/Profile.jpg
