title: home | isaac broyles
description: isaac broyles home
show_downloads: true
google_analytics:
theme: jekyll-theme-hydeout
repository: 'isaacbroyles/isaacbroyles.github.io'
include: [".well-known"]