title: home | isaac broyles
description: Software Engineering
show_downloads: true
google_analytics:
theme: jekyll-theme-hydeout
repository: 'isaacbroyles/isaacbroyles.github.io'
include: [".well-known"]
paginate: 5
sass:
    sass_dir: ./_scss