title: home | isaac broyles
description: Software Engineering
show_downloads: true
google_analytics: 'UA-122362865-1'
repository: 'isaacbroyles/isaacbroyles.github.io'
include: [".well-known"]
paginate: 5
url: "https://www.isaacbroyles.com"
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap